const commonWords = {
    the: true,
    of: true,
    and: true,
    a: true,
    to: true,
    in: true,
    is: true,
    as: true,
    that: true,
    his: true,
    with: true,
    by: true,
    from: true,
    it: true,
    he: true,
    for: true,
    are: true,
    its: true,
    this: true,
    an: true,
    be: true,
    their: true,
    there: true,
    on: true,
    was: true,
    not: true,
    or: true,
    but: true,
    they: true,
    her: true
}

module.exports.commonWords = commonWords;